### ISSUE TITLE
The output of 'predict_faces' is null 

### ISSUE THREAD

**Issue by MindLostGuy** [manycore-research/faceformer#2]
I used the 'ours.yml' setting, yet in the output json file, [predict_face] turns out to be null. 
Thus, i can hardly use the output json to reconstruct the wireframe or mesh.

**Comment by Jason-Khan** [comment]
Hi,

Thanks for checking out our repo. Could you list the series of commands you used so we can replicate the bug?

Kehan

**Comment by MindLostGuy** [comment]
conda env create --file environment.yml
python main.py --config-file configs/ours.yml --test_ckpt trained_models/ours.ckpt
Then in the output json the [predict_face] turns to be [], the null.

I simply modify the 'root dir' in the yml file.
By the way, I think there might be some problem if you load the pretrained model , the root dir will unpredictable set to a unseen way, which might be set in the ckpt file.
I figure the problem by modifying the main.py line 46: model = Trainer().load_checkpoint() into 
model = Trainer() and model.load_checkpoint().
That's my input commands and the changed python files.

**Comment by MindLostGuy** [comment]
The torch version is upgraded to 1.8.0, the cudatoolkit is upgraded to 11.1.1.
The previous env setting will result in "OSError: undefined symbol: free_gemm_select"

**Comment by MindLostGuy** [comment]
Is there any solution? Thanks

**Comment by Jason-Khan** [comment]
Hi,

Very sorry for the late reply. I was able to produce face predictions with [ours.ckpt](https://drive.google.com/drive/folders/1oEoN_GzS36obLjvOlwFrOpWo0N7oh-fS) and [data_ours.tar.gz](https://drive.google.com/drive/folders/1ynMD02E5FWlCPmQkWyjHdq4Zhe8DIXE2). I think there may have been some data issues that led to null predicted faces. I have updated the code base and the latest code may resolve these issues. Please pull the latest code and try the following:

- *Why does root_dir not update when I change it in configs/ours.yml?*
Seems like when pytorch_lightning loads the checkpoint in, it also uses the old root dir which we trained the model with.
To fix: Please uncomment line 25 of faceformer/trainer.py and set the desired root_dir there.

- *How should I use the downloaded json dataset?*
Sorry for the incomplete documentation for existing json datasets from [here](https://drive.google.com/drive/folders/1ynMD02E5FWlCPmQkWyjHdq4Zhe8DIXE2). Assuming we have downloaded *data_ours.tar.gz* and unzipped it to the same directory as split_json.py in the outer-most directory, we now have:

  ```
  root
  ├── main.py
  ├── split_json.py
  ├── ours
  │   └── 00000050.json
  │   └── 00000052.json
  │   └── ...
  ```
  
  Run `python split_json.py` and it should prepare the dataset into the following:
  
  ```
  root
  ├── main.py
  ├── split_json.py
  ├── ours
  │   └── test.txt
  │   └── train.txt
  │   └── valid.txt
  │   └── json
  │       └── 00000050.json
  │       └── 00000052.json
  │       └── ...
  ```
  
  With this, set the root_dir to "ours" at line 25 of faceformer/trainer.py, and 
  ```
  python main.py --config-file configs/ours.yml --test_ckpt trained_models/ours.ckpt
  ```
  should work.

Let me know if there are any additional errors!

Kehan

**Comment by MindLostGuy** [comment]
Thanks for reply. The problem has solved.
It's strange that when I try to train from scratch, there are outputs during validation. Both the training scalars and validation scalars are fine during training. But when I try to validate alone, the validation score drops from 0.9 to 0.
But now it works. It works when I set the root_dir alone and reset main.py.
